export enum EstadoPistaEnum {
    REVISION_MANUAL= 'REVISION_MANUAL',
    RECHAZADO= 'RECHAZADO',
    DESCARTADO= 'DESCARTADO',
    PRE_APROBADO= 'PRE_APROBADO',
    DUPLICADO= 'DUPLICADO',
    COMPLETADO= 'COMPLETADO',
    INPROCESS= 'INPROCESS',
    APROBADO= 'APROBADO',
    VINCULAR= 'VINCULAR',
    CANCELADO= 'CANCELADO',
    TODO = 'TODO'
}